// let set=new Set();
// set.add(100);
// set.add(100);
// console.log(set);
const map =new Map();
map.set("html",3);
map.set("css",5);
map.set("js",10);
map.set("nodejs",10);
const {html,css,js,nodejs}=map;
console.log(html,css,js,nodejs);